# Generated by Django 5.0.6 on 2025-07-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('air_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('coe_fed', models.CharField(blank=True, max_length=100, null=True)),
                ('complexity', models.CharField(blank=True, max_length=50, null=True)),
                ('tool_version', models.CharField(blank=True, max_length=200, null=True)),
                ('process_details', models.TextField(blank=True, null=True)),
                ('object_details', models.TextField(blank=True, null=True)),
                ('queue', models.CharField(blank=True, max_length=200, null=True)),
                ('shared_folders', models.TextField(blank=True, null=True)),
                ('shared_mailboxes', models.TextField(blank=True, null=True)),
                ('qa_handshake', models.CharField(blank=True, max_length=200, null=True)),
                ('preprod_deploy_date', models.DateTimeField(blank=True, null=True)),
                ('prod_deploy_date', models.DateTimeField(blank=True, null=True)),
                ('warranty_end_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('documentation', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'automations',
                'ordering': ['-created_at'],
            },
        ),
    ]
