# Generated by Django 5.0.6 on 2025-07-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_person_tool_automation_path_artifacts_environment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('import', 'Import'), ('export', 'Export'), ('bulk_create', 'Bulk Create'), ('search', 'Search'), ('view', 'View')], max_length=20)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('object_name', models.CharField(blank=True, max_length=500, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
